import { IconOptionType } from "../types";

export const ICON_OPTIONS: IconOptionType[] = [
  {
    npm: "MaterialCommunityIcons",
    icon: "google",
    bgColor: "#4285f4",
    color: "#ffffff",
    title: "Google",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "github",
    bgColor: "#24292e",
    color: "#ffffff",
    title: "GitHub",
  },
  {
    npm: "Custom",
    icon: "amazon",
    bgColor: "#ff9900",
    color: "#ffffff",
    title: "Amazon",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "youtube",
    bgColor: "#ff0000",
    color: "#ffffff",
    title: "YouTube",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "facebook",
    bgColor: "#1877f2",
    color: "#ffffff",
    title: "Facebook",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "twitter",
    bgColor: "#1da1f2",
    color: "#ffffff",
    title: "Twitter",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "linkedin",
    bgColor: "#0a66c2",
    color: "#ffffff",
    title: "LinkedIn",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "apple",
    bgColor: "#000000",
    color: "#ffffff",
    title: "Apple",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "microsoft",
    bgColor: "#00a4ef",
    color: "#ffffff",
    title: "Microsoft",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "dropbox",
    bgColor: "#0061ff",
    color: "#ffffff",
    title: "Dropbox",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "reddit",
    bgColor: "#ff4500",
    color: "#ffffff",
    title: "Reddit",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "instagram",
    bgColor: "#e4405f",
    color: "#ffffff",
    title: "Instagram",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "key",
    bgColor: "#6366f1",
    color: "#ffffff",
    title: "Key",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "shield",
    bgColor: "#8b5cf6",
    color: "#ffffff",
    title: "Shield",
  },
  {
    npm: "MaterialCommunityIcons",
    icon: "lock",
    bgColor: "#ec4899",
    color: "#ffffff",
    title: "Lock",
  },
  {
    npm: "Custom",
    icon: "globe",
    bgColor: "#14b8a6",
    color: "#ffffff",
    title: "Globe",
  },
];
